[global]
simulation_name = multiple_populations    ; A arbitrary identifier for the simulation
num_populations = 11         ; total number of populations to model
simulation_runs = 20         ; total number of runs to obtain proper statistics


[disease]              ; Global disease configuration
name = "Corona"        ; Name of the disease
duration = 7          ; Days a person is infectious 
transmissability = 0.2 ; Probability of the disease being transmitted on contact

; For each population a section is added
[population_1]         ; 
name = Deggendorf    ;  
size = 15000           ;
vaccination_rate = 0.88 ;
patient_0 = true       ;

[population_2]         ; 
name = Regensburg    ;  
size = 15000           ;
vaccination_rate = 0.1  ;
patient_0 = true       ;

[population_3]         ; 
name = Zwiesel    ;  
size = 15000           ;
vaccination_rate = 0.2  ;
patient_0 = true       ;

[population_4]         ; 
name = Passau    ;  
size = 15000           ;
vaccination_rate = 0.3  ;
patient_0 = true       ;

[population_5]         ; 
name = Cairo    ;  
size = 15000           ;
vaccination_rate = 0.4  ;
patient_0 = true       ;

[population_6]         ; 
name = Alex    ;  
size = 15000           ;
vaccination_rate = 0.5  ;
patient_0 = true       ;

[population_7]         ; 
name = Munich    ;  
size = 15000           ;
vaccination_rate = 0.6  ;
patient_0 = true       ;

[population_8]         ; 
name = Stuttgart    ;  
size = 15000           ;
vaccination_rate = 0.7  ;
patient_0 = true       ;

[population_9]         ; 
name = Magdburg    ;  
size = 15000           ;
vaccination_rate = 0.8  ;
patient_0 = true       ;

[population_10]         ; 
name = NoName    ;  
size = 15000           ;
vaccination_rate = 0.9  ;
patient_0 = true       ;

[population_11]         ; 
name = NewName    ;  
size = 15000           ;
vaccination_rate = 1.0  ;
patient_0 = false       ;
