[global]
simulation_name = multiple_populations    ; A arbitrary identifier for the simulation
num_populations = 5         ; total number of populations to model
simulation_runs = 20         ; total number of runs to obtain proper statistics


[disease]              ; Global disease configuration
name = "Corona"        ; Name of the disease
duration = 30          ; Days a person is infectious 
transmissability = 1.0 ; Probability of the disease being transmitted on contact

; For each population a section is added
[population_1]         ; 
name = Deggendorf    ;  
size = 20000000            ;
vaccination_rate = 0.0 ;
patient_0 = true       ;

[population_2]         ; 
name = Regensburg    ;  
size = 5000000           ;
vaccination_rate = 0.0  ;
patient_0 = true       ;

[population_3]         ; 
name = Zwiesel    ;  
size = 5000000           ;
vaccination_rate = 0.0  ;
patient_0 = true       ;

[population_4]         ; 
name = Passau    ;  
size = 4000000           ;
vaccination_rate = 0.0  ;
patient_0 = true       ;

[population_5]         ; 
name = TEST_POP    ;  
size = 3000000           ;
vaccination_rate = 0.1  ;
patient_0 = true       ;
